### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by drforbin** [pkoning2/pydecnet#1]
hey there

I'm getting this when I try and install

Traceback (most recent call last):
  File "/home/falcon/pydecnet/pydecnet/./setup.py", line 19, in <module>
    version = getrevision (),
  File "/home/falcon/pydecnet/pydecnet/decnet/main.py", line 128, in getrevision
    http.setdnrev ()
  File "/home/falcon/pydecnet/pydecnet/decnet/http.py", line 53, in setdnrev
    r = revno (r)
  File "/home/falcon/pydecnet/pydecnet/decnet/http.py", line 34, in revno
    return int (s.split ()[1])
IndexError: list index out of range

l

**Comment by pkoning2** [comment]
I take it you did a checkout of the repository.  I forgot to mention that I have not yet merged the t1.1 branch into the main branch (I will do that at release).  So the default branch "main" is the V1.0 code, and that doesn't handle the case of being in a Git repository workspace.  (It expects Subversion.)
So do "git checkout t1.1" to switch to the t1.1 branch, then it should work.

**Comment by drforbin** [comment]
thxs

**Comment by drforbin** [comment]
ok. I got it installed... I installed the lib from the previous branch, is that ok?

**Comment by pkoning2** [comment]
Installed what lib?

Originally I had pylibcap and daemon libraries included with pydecnet because there weren't ones in the standard library packages that seemed right.  That is no longer true (hasn't been for a while).  

As described in install.txt, if you want the "daemon" feature, you need to install the "python-daemon" package with pip.  As for libpcap, that's all built in now, it doesn't have any dependencies.  Well, other than having libpcap installed in your host, say by installing "tcpdump" or "wireshark".

**Comment by drforbin** [comment]
The pylibcap

**Comment by drforbin** [comment]
Ok..what do I do now to connect with you?

**Comment by pkoning2** [comment]
I don't think installing pylibpcap is any problem, it shouldn't be used.  But it wasn't necessary, which is why I removed it.
